- hosts: aws
  tasks:
#    - name: Set authorized key for user {{ ansible_user }} copying it from current user
#      authorized_key:
#        user: "{{ ansible_user }}"
#        state: present
#        key: "{{ lookup('file', '{{ ansible_ssh_private_key_file }}') }}"
    # task 1
    - name: test connection
      args:
        chdir: "{{ dir }}/Stock_analysis"
      shell: pwd
      register: message

    # task 2
    - name: print debug message
      debug:
        msg: "{{ message }}"