- hosts: aws
  tasks:
#    - name: Set authorized key for user {{ ansible_user }} copying it from current user
#      authorized_key:
#        user: "{{ ansible_user }}"
#        state: present
#        key: "{{ lookup('file', '{{ ansible_ssh_private_key_file }}') }}"
#    # task 1
#    - name: test connection
#      args:
#        chdir: "/home/ubuntu/Stock_analysis"
#      shell: pwd
#      register: message
#
    # task
    - name: git pull
      git:
        repo: "https://github.com/kobe65218/Stock_analysis.git"
        dest: /home/ec2-user/Stock_analysis
        update: yes
        version: docker

    - name: Down container
      become: True
      shell:
          chdir: /home/ec2-user/Stock_analysis
          cmd: docker-compose down
      register: message


    - name : make file
      become: True
      shell:
        chdir: /home/ec2-user/Stock_analysis
        cmd: mkdir ./logs ./plugins

    - name: set env
      become: True
      shell:
        chdir: /home/ec2-user/Stock_analysis
        cmd: echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env


    - name: init airflow
      become: True
      shell:
        chdir: /home/ec2-user/Stock_analysis
        cmd: docker-compose up airflow-init


    - name: up container
      become: True
      shell:
        cmd: docker-compose  up -d
        chdir: /home/ec2-user/Stock_analysis

#    # task 2
#    - name: print debug message
#      debug:
#        msg: "{{ message }}"


#    - name: git pull
#      become: True
#      shell:
#        cmd: "git pull"
#        chdir: "/home/ubuntu/Stock_analysis"
#
#
#    - name: up container
#      become: True
#      shell:
#        cmd: "docker-compose up stock_dashboard"
#        chdir: "/home/ubuntu/Stock_analysis"