- hosts: gwc
  become: True

  tasks:
    ## 確認
    - name: check docker is installed
      shell: docker --version
      register: check_docker
      ignore_errors: True

    - name: install docker
      include_role:
        name: docker
      when: check_docker.rc != 0


    - name: check docker-compose is installed
      shell: docker-compose --version
      register: check_docker_compose
      ignore_errors: True

    - name: install docker-compose
      include_role:
        name: docker-compose
      when: check_docker_compose.rc != 0

    - name: git pull
      git:
        repo: "https://github.com/kobe65218/Stock_analysis.git"
        dest: /home/kobe655218/Stock_analysis
        update: yes
        version: docker

    - name: Down container
      become: True
      shell:
        chdir: /home/kobe655218/Stock_analysis
        cmd: docker-compose down
      register: message


    - name: set env
      become: True
      shell:
        chdir: /home/kobe655218/Stock_analysis
        cmd: echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env


    - name: init airflow
      become: True
      shell:
        chdir: /home/kobe655218/Stock_analysis
        cmd: docker-compose up airflow-init


    - name: up container
      become: True
      shell:
        cmd: docker-compose  up -d
        chdir: /home/kobe655218/Stock_analysis
