- hosts: gwc
  become: True

  tasks:
    # 檢查docker是否安裝
    - name: check docker is installed
      shell: docker --version
      register: check_docker
      ignore_errors: True

    # 如果沒安裝在安裝docker
    - name: install docker
      include_role:
        name: docker
      when: check_docker.rc != 0

     # 檢查docker-compose是否安裝
    - name: check docker-compose is installed
      shell: docker-compose --version
      register: check_docker_compose
      ignore_errors: True

     # 如果沒安裝在安裝docker-compose
    - name: install docker-compose
      include_role:
        name: docker-compose
      when: check_docker_compose.rc != 0

    # 從git pull 最新code
    - name: git pull
      git:
        repo: "https://github.com/kobe65218/Stock_analysis.git"
        dest: /home/kobe655218/Stock_analysis
        update: yes
        version: docker

    # docker-compose down
    - name: docker-compose down
      become: True
      shell:
        chdir: /home/kobe655218/Stock_analysis
        cmd: docker-compose down
      register: message


#    - name: set env
#      become: True
#      shell:
#        chdir: /home/kobe655218/Stock_analysis
#        cmd: echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env
#
#    - name: create a directory, and set the permissions
#      become: True
#      ignore_errors: True
#      file:
#        path: "/home/kobe655218/Stock_analysis/{{ item }}"
#        state: directory
#        owner: kobe655218
#        group: kobe655218
#        mode: "777"
#
#
#      loop:
#        - logs
#        - plugins
#
#    - name: create a directory, and set the permissions
#      become: True
#      file:
#        path: "/home/kobe655218/Stock_analysis/{{ item }}"
#        owner: kobe655218
#        group: kobe655218
#        mode: "777"
#      loop:
#        - .env
#
#    # 初始化airflow
#    - name: init airflow
#      become: True
#      shell:
#        chdir: /home/kobe655218/Stock_analysis
#        cmd: docker-compose up airflow-init

    # 建置airflow以及flask app
    - name: up container
      become: True
      shell:
        cmd: docker-compose up -d stock_dashboard
        chdir: /home/kobe655218/Stock_analysis
